name: .NET Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release --no-restore
    - name: Publish-AOT
      run: dotnet publish --property:OutputPath=.\publish\
    - name: Upload-AOT
      uses: actions/upload-artifact@v4
      with:
        name: Artifacts-AOT
        path: YaeAchievement\publish\publish
    - name: Publish-NoAOT
      run: dotnet publish --property:OutputPath=.\naot-publish\ --property:PublishAot=false --property:PublishSingleFile=true --property:PublishTrimmed=true
    - name: Upload-NoAOT
      uses: actions/upload-artifact@v4
      with:
        name: Artifacts-NoAOT
        path: YaeAchievement\naot-publish\publish
